// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/health": {
    params: {};
  };
  "/users/:id": {
    params: {
      "id": string;
    };
  };
  "/checkout": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/health" | "/users/:id" | "/checkout";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/health.tsx": {
    id: "routes/health";
    page: "/health";
  };
  "routes/users.$id.tsx": {
    id: "routes/users.$id";
    page: "/users/:id";
  };
  "routes/checkout.tsx": {
    id: "routes/checkout";
    page: "/checkout";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/health": typeof import("./app/routes/health.tsx");
  "routes/users.$id": typeof import("./app/routes/users.$id.tsx");
  "routes/checkout": typeof import("./app/routes/checkout.tsx");
};